### ISSUE TITLE
Time is not the same, showing for New York...

### ISSUE THREAD

**Issue by justjim1220** [mykle1/MMM-Clockinese#1]
This is what I'm Talking about...

![screenshot 16](https://user-images.githubusercontent.com/27590633/43422332-01214d76-940f-11e8-9ae5-6835ec4d8f20.png)

and if I click on it, it brings me to this...

![screenshot 17](https://user-images.githubusercontent.com/27590633/43422383-285e8a8e-940f-11e8-9d15-1dd35a655dcf.png)

**Comment by justjim1220** [comment]
Also... How do I make it bigger???

**Comment by mykle1** [comment]
Ok, you're gonna have to do some of the work here if it's that important to you. :-)

Go to https://www.timeanddate.com/clocks/free.html and design the clock you want. The site will generate a url for you. The url has to be added to the MMM-Clockinese.js file, replacing the existing one. Then adjust the height and width to match the new clock. Let me know how you do. I'm going to close this issue
